import fs from 'fs/promises';
import { ConversionSettings } from '../../../shared/types';
import { ProcessedImageData, PixelData } from './imageProcessor.service';
import logger from '../utils/logger';

export class SVGGeneratorService {
  /**
   * Generate SVG from pixel grid
   */
  async generateSVG(
    imageData: ProcessedImageData,
    settings: ConversionSettings,
    outputPath: string,
    maxDimension?: number
  ): Promise<void> {
    const startTime = Date.now();
    logger.info('Generating SVG output');

    const { pixelGrid, palette, gridWidth, gridHeight, width, height } = imageData;

    // Calculate SVG dimensions
    let svgWidth: number, svgHeight: number;

    if (maxDimension) {
      const shorterSide = Math.min(width, height);
      const scale = maxDimension / shorterSide;
      svgWidth = Math.round(width * scale);
      svgHeight = Math.round(height * scale);
    } else {
      svgWidth = width;
      svgHeight = height;
    }

    // Calculate block size
    const blockWidth = svgWidth / gridWidth;
    const blockHeight = svgHeight / gridHeight;

    let svgContent = this.generateSVGHeader(svgWidth, svgHeight);

    if (settings.mode === 'color' && palette) {
      // Group rectangles by color for easier editing in vector software
      svgContent += this.generateGroupedColorSVG(pixelGrid, blockWidth, blockHeight, palette);
    } else {
      // Simple B&W output
      svgContent += this.generateSimpleSVG(pixelGrid, blockWidth, blockHeight);
    }

    svgContent += '</svg>';

    await fs.writeFile(outputPath, svgContent, 'utf-8');

    const processingTime = Date.now() - startTime;
    logger.info(`SVG generated in ${processingTime}ms`);
  }

  /**
   * Generate SVG header
   */
  private generateSVGHeader(width: number, height: number): string {
    return `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg"
     width="${width}"
     height="${height}"
     viewBox="0 0 ${width} ${height}"
     version="1.1">
  <title>Bitmap Pixelator Output</title>
  <desc>Generated by Bitmap Pixelator - https://bitmappixelator.com</desc>
`;
  }

  /**
   * Generate simple SVG (for B&W mode or ungrouped color)
   */
  private generateSimpleSVG(
    pixelGrid: PixelData[][],
    blockWidth: number,
    blockHeight: number
  ): string {
    let content = '  <g id="pixels">\n';

    for (let y = 0; y < pixelGrid.length; y++) {
      for (let x = 0; x < pixelGrid[y].length; x++) {
        const pixel = pixelGrid[y][x];

        // Skip white pixels in B&W mode to reduce file size
        if (pixel.hex === '#ffffff') {
          continue;
        }

        const rectX = x * blockWidth;
        const rectY = y * blockHeight;

        content += `    <rect x="${rectX.toFixed(2)}" y="${rectY.toFixed(2)}" width="${blockWidth.toFixed(2)}" height="${blockHeight.toFixed(2)}" fill="${pixel.hex}"/>\n`;
      }
    }

    content += '  </g>\n';
    return content;
  }

  /**
   * Generate grouped SVG by color (for color mode)
   */
  private generateGroupedColorSVG(
    pixelGrid: PixelData[][],
    blockWidth: number,
    blockHeight: number,
    palette: string[]
  ): string {
    let content = '';

    // Create a group for each color in the palette
    for (const color of palette) {
      content += `  <g id="color-${color.substring(1)}" fill="${color}">\n`;

      // Find all pixels with this color
      for (let y = 0; y < pixelGrid.length; y++) {
        for (let x = 0; x < pixelGrid[y].length; x++) {
          const pixel = pixelGrid[y][x];

          if (pixel.hex.toLowerCase() === color.toLowerCase()) {
            const rectX = x * blockWidth;
            const rectY = y * blockHeight;

            content += `    <rect x="${rectX.toFixed(2)}" y="${rectY.toFixed(2)}" width="${blockWidth.toFixed(2)}" height="${blockHeight.toFixed(2)}"/>\n`;
          }
        }
      }

      content += '  </g>\n';
    }

    return content;
  }

  /**
   * Generate optimized SVG using paths instead of rectangles (smaller file size)
   */
  async generateOptimizedSVG(
    imageData: ProcessedImageData,
    settings: ConversionSettings,
    outputPath: string,
    maxDimension?: number
  ): Promise<void> {
    const startTime = Date.now();
    logger.info('Generating optimized SVG output');

    const { pixelGrid, palette, gridWidth, gridHeight, width, height } = imageData;

    // Calculate SVG dimensions
    let svgWidth: number, svgHeight: number;

    if (maxDimension) {
      const shorterSide = Math.min(width, height);
      const scale = maxDimension / shorterSide;
      svgWidth = Math.round(width * scale);
      svgHeight = Math.round(height * scale);
    } else {
      svgWidth = width;
      svgHeight = height;
    }

    // Calculate block size
    const blockWidth = svgWidth / gridWidth;
    const blockHeight = svgHeight / gridHeight;

    let svgContent = this.generateSVGHeader(svgWidth, svgHeight);

    if (settings.mode === 'color' && palette) {
      svgContent += this.generateOptimizedColorPaths(pixelGrid, blockWidth, blockHeight, palette);
    } else {
      svgContent += this.generateOptimizedBWPaths(pixelGrid, blockWidth, blockHeight);
    }

    svgContent += '</svg>';

    await fs.writeFile(outputPath, svgContent, 'utf-8');

    const processingTime = Date.now() - startTime;
    logger.info(`Optimized SVG generated in ${processingTime}ms`);
  }

  /**
   * Generate optimized paths for B&W mode
   */
  private generateOptimizedBWPaths(
    pixelGrid: PixelData[][],
    blockWidth: number,
    blockHeight: number
  ): string {
    let content = '  <g id="pixels">\n';

    // Combine adjacent pixels of the same color into paths
    const visited = Array.from({ length: pixelGrid.length }, () =>
      Array(pixelGrid[0].length).fill(false)
    );

    for (let y = 0; y < pixelGrid.length; y++) {
      for (let x = 0; x < pixelGrid[y].length; x++) {
        if (visited[y][x]) continue;

        const pixel = pixelGrid[y][x];

        // Skip white pixels in B&W mode
        if (pixel.hex === '#ffffff') {
          visited[y][x] = true;
          continue;
        }

        // Find horizontal run of same color
        let width = 1;
        while (
          x + width < pixelGrid[y].length &&
          !visited[y][x + width] &&
          pixelGrid[y][x + width].hex === pixel.hex
        ) {
          width++;
        }

        // Mark as visited
        for (let i = 0; i < width; i++) {
          visited[y][x + i] = true;
        }

        const rectX = x * blockWidth;
        const rectY = y * blockHeight;
        const rectWidth = width * blockWidth;

        content += `    <rect x="${rectX.toFixed(2)}" y="${rectY.toFixed(2)}" width="${rectWidth.toFixed(2)}" height="${blockHeight.toFixed(2)}" fill="${pixel.hex}"/>\n`;
      }
    }

    content += '  </g>\n';
    return content;
  }

  /**
   * Generate optimized paths for color mode
   */
  private generateOptimizedColorPaths(
    pixelGrid: PixelData[][],
    blockWidth: number,
    blockHeight: number,
    palette: string[]
  ): string {
    let content = '';

    for (const color of palette) {
      content += `  <g id="color-${color.substring(1)}" fill="${color}">\n`;

      const visited = Array.from({ length: pixelGrid.length }, () =>
        Array(pixelGrid[0].length).fill(false)
      );

      for (let y = 0; y < pixelGrid.length; y++) {
        for (let x = 0; x < pixelGrid[y].length; x++) {
          if (visited[y][x] || pixelGrid[y][x].hex.toLowerCase() !== color.toLowerCase()) {
            continue;
          }

          // Find horizontal run
          let width = 1;
          while (
            x + width < pixelGrid[y].length &&
            !visited[y][x + width] &&
            pixelGrid[y][x + width].hex.toLowerCase() === color.toLowerCase()
          ) {
            width++;
          }

          // Mark as visited
          for (let i = 0; i < width; i++) {
            visited[y][x + i] = true;
          }

          const rectX = x * blockWidth;
          const rectY = y * blockHeight;
          const rectWidth = width * blockWidth;

          content += `    <rect x="${rectX.toFixed(2)}" y="${rectY.toFixed(2)}" width="${rectWidth.toFixed(2)}" height="${blockHeight.toFixed(2)}"/>\n`;
        }
      }

      content += '  </g>\n';
    }

    return content;
  }

  /**
   * Get SVG as string (for small outputs that can be sent inline)
   */
  async getSVGString(
    imageData: ProcessedImageData,
    settings: ConversionSettings,
    maxDimension?: number
  ): Promise<string> {
    const { pixelGrid, palette, gridWidth, gridHeight, width, height } = imageData;

    // Calculate SVG dimensions
    let svgWidth: number, svgHeight: number;

    if (maxDimension) {
      const shorterSide = Math.min(width, height);
      const scale = maxDimension / shorterSide;
      svgWidth = Math.round(width * scale);
      svgHeight = Math.round(height * scale);
    } else {
      svgWidth = width;
      svgHeight = height;
    }

    // Calculate block size
    const blockWidth = svgWidth / gridWidth;
    const blockHeight = svgHeight / gridHeight;

    let svgContent = this.generateSVGHeader(svgWidth, svgHeight);

    if (settings.mode === 'color' && palette) {
      svgContent += this.generateGroupedColorSVG(pixelGrid, blockWidth, blockHeight, palette);
    } else {
      svgContent += this.generateSimpleSVG(pixelGrid, blockWidth, blockHeight);
    }

    svgContent += '</svg>';

    return svgContent;
  }
}

export default new SVGGeneratorService();
